"""Initial metadata

Revision ID: 100f64d6906c
Revises: 
Create Date: 2020-11-29 23:47:14.220044

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "100f64d6906c"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "respondents",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column(
            "messenger",
            sa.Enum("telegram", "viber", "whatapp", name="messengers"),
            nullable=False,
        ),
        sa.Column("username", sa.String(), nullable=True),
        sa.Column("first_name", sa.String(), nullable=True),
        sa.Column("last_name", sa.String(), nullable=True),
        sa.Column("extra_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.PrimaryKeyConstraint("id", "messenger"),
    )
    op.create_table(
        "dialogs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "cancelled", sa.Boolean(), server_default=sa.text("false"), nullable=True
        ),
        sa.Column(
            "completed", sa.Boolean(), server_default=sa.text("false"), nullable=True
        ),
        sa.Column("respondent_id", sa.String(), nullable=False),
        sa.Column(
            "respondent_messenger",
            sa.Enum("telegram", "viber", "whatapp", name="messengers"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["respondent_id", "respondent_messenger"],
            ["respondents.id", "respondents.messenger"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_dialog_fk_respondent",
        "dialogs",
        ["respondent_id", "respondent_messenger"],
        unique=False,
    )
    op.create_table(
        "dialogue_steps",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("dialog_id", sa.Integer(), nullable=False),
        sa.Column("question", sa.String(), nullable=False),
        sa.Column("answer", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["dialog_id"],
            ["dialogs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_dialogue_steps_fk_dialog", "dialogue_steps", ["dialog_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_dialogue_steps_fk_dialog", table_name="dialogue_steps")
    op.drop_table("dialogue_steps")
    op.drop_index("idx_dialog_fk_respondent", table_name="dialogs")
    op.drop_table("dialogs")
    op.drop_table("respondents")
    # ### end Alembic commands ###
