"""Added called_functions table

Revision ID: 25fb7f9892ad
Revises: c290779b8a98
Create Date: 2021-10-30 20:00:22.667846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25fb7f9892ad'
down_revision = '76b3fed43166'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('called_functions',
    sa.Column('hash', sa.BigInteger(), nullable=False),
    sa.Column('dialog_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['dialog_id'], ['dialogs.id'], ),
    sa.PrimaryKeyConstraint('hash', 'dialog_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('called_functions')
    # ### end Alembic commands ###
